modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License 3"

[[mods]]
modId="backpacker"
version="1.2.3"
displayName="Backpacker"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/backpacker/update.json"
displayURL="https://mrcrayfish.com/mods?id=backpacker"
logoFile="backpacker.png"
credits=""
authors="MrCrayfish"
description="An addon for Backpacked that adds more variants of backpacks"
itemIcon="backpacker:shulkerpack"
configBackground="minecraft:textures/block/cobblestone.png"

[[dependencies.backpacker]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacker]]
    modId="backpacked"
    mandatory=true
    versionRange="[1.7.0,)"
    ordering="AFTER"
    side="BOTH"