modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License 3"
issueTrackerURL="https://github.com/MrCrayfish/Backpacker/issues"

[[mods]]
modId="backpacker"
version="1.3.1"
displayName="Backpacker"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=backpacker"
displayURL="https://mrcrayfish.com/mods?id=backpacker"
logoFile="backpacker.png"
credits=""
authors="MrCrayfish"
description="An addon for Backpacked that adds more variants of backpacks"

[[dependencies.backpacker]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacker]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.backpacker]]
    modId="backpacked"
    mandatory=true
    versionRange="[1.7.0,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.backpacker]
    catalogueItemIcon="backpacker:shulkerpack"
    configuredBackground="minecraft:textures/block/cobblestone.png"